# This is a config for E2B sandbox template.
# You can use template ID (wl0gm6wo6qwpgclpi939) or template name (vibe-nextjs-test-ai) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-ai") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-ai") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-ai')

team_id = "1ef0e5de-05eb-4217-bd1a-ea17835adadf"
start_cmd = "bash /code/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-ai"
template_id = "wl0gm6wo6qwpgclpi939"
