# This is a config for E2B sandbox template.
# You can use template ID (1uyojpjcxg4j0agwl2d7) or template name (vibe-nextjs-test-01) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-01") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-01") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-01')

team_id = "1ef0e5de-05eb-4217-bd1a-ea17835adadf"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-01"
template_id = "1uyojpjcxg4j0agwl2d7"
